/*
 * AEB_Interface.h
 *
 *  Created on: Mar 20, 2024
 *      Author: Abdallah Essam
 */

#ifndef APPLICATION_AUTOMATICEMERGENCYBRAKING_AEB_INTERFACE_H_
#define APPLICATION_AUTOMATICEMERGENCYBRAKING_AEB_INTERFACE_H_

void APP_AEB_vTask();

#endif /* APPLICATION_AUTOMATICEMERGENCYBRAKING_AEB_INTERFACE_H_ */
